version: '3.3'
services:
  web:
    build:
      context: configs
      dockerfile: Dockerfile
    volumes:
      - ./projecto_failai:/var/www/html/
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      APACHE_SERVER_NAME: kcs
      APPLICATION_ENV: development

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kcs_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 81:80
    environment:
      PMA_HOST: db
      PMA_USER: devuser
      PMA_PASSWORD: devpass
      UPLOAD_LIMIT: 2048

  composer:
    image: composer
    command: ["composer", "install"]
    volumes:
      - ./projecto_failai:/var/www/html/
